### ISSUE TITLE
TypeError: object of type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by imowa** [img88/Microstock-Keyword-Suggestion#1]
1 # jumlah kemunculan setiap keyword
      2 keyword_gabungan = metadata.Keyword.sum()
----> 3 print("jumlah seluruh keyword:", len(keyword_gabungan))
      4 print("jumlah keyword unik:", pd.Series(metadata["Keyword"].sum()).nunique())

TypeError: object of type 'numpy.float64' has no len()

solusinya bang?
terima kasih

**Comment by img88** [comment]
> 1 # jumlah kemunculan setiap keyword 2 keyword_gabungan = metadata.Keyword.sum() ----> 3 print("jumlah seluruh keyword:", len(keyword_gabungan)) 4 print("jumlah keyword unik:", pd.Series(metadata["Keyword"].sum()).nunique())
> 
> TypeError: object of type 'numpy.float64' has no len()
> 
> solusinya bang? terima kasih

**Comment by img88** [comment]
> 1 # jumlah kemunculan setiap keyword 2 keyword_gabungan = metadata.Keyword.sum() ----> 3 print("jumlah seluruh keyword:", len(keyword_gabungan)) 4 print("jumlah keyword unik:", pd.Series(metadata["Keyword"].sum()).nunique())
> 
> TypeError: object of type 'numpy.float64' has no len()
> 
> solusinya bang? terima kasih

Kodenya sudah lama tidak update seiring webnya yang sudah berubah, mungkin harus diubah dibagian scrapingnya
